// SPDX-License-Identifier: CC0-1.0
// Public-domain example code (CC0) - see LICENSE. The CAS BACnet Stack itself is
// a separate, commercially licensed product and is not covered by CC0.
// =============================================================================
// BACnet Profile Example - B-SS (BACnet Smart Sensor) - C++
//
// This example shows the *minimum* needed to implement the BACnet "B-SS"
// (Smart Sensor) device profile with the CAS BACnet Stack.
//
// A B-SS is "a simple sensing device with very limited resources" (ANSI/ASHRAE
// 135, Annex L.4.5). Its only mandatory capability is:
//
//     DS-RP-B  - respond to ReadProperty requests
//
// plus the ability to be discovered: it answers Who-Is with I-Am (handled
// automatically by the stack) and announces itself with an unsolicited I-Am on
// start-up.
//
// A B-SS does NOT require WriteProperty, COV, alarms/events, scheduling, or
// trending - so this example deliberately does NOT enable any of those. That is
// the whole point of a profile example: implement exactly what the profile
// asks for, nothing more.
//
// The device exposes three read-only sensor objects plus the Network Port
// object that every BACnet device must have. Each object is given a colour name
// (a convention shared across this example series):
//
//     Device 389001          "Rainbow"    (instance configurable with --deviceID)
//     Analog Input  1        "Bronze"     (REAL, degrees Celsius; starts at 21.5)
//     Binary Input  1        "Emerald"    (active / inactive)
//     Multi-State Input 1    "Hot Pink"   (an enumerated state, 1..3)
//     Network Port 1         "Vermilion"  (the BACnet/IP port - required)
//
// To be a conformant BACnet device (Protocol_Revision 24) each object must
// expose its full set of REQUIRED properties. Most are generated by the stack
// (Object_Identifier, Object_Type, Status_Flags, Event_State, Object_List,
// Protocol_*). The handful that the application must supply are served by the
// Get*Property callbacks below, and a few are turned on with SetPropertyEnabled.
//
// Interactive keys (handled by common/CASExampleEditor): h = help, q = quit,
// e = edit mode (pick an object, then up/down/space to change its value).
// Command line: --port <n>, --deviceID <n>.
//
// All the UDP/stack plumbing lives in common/CASExampleHelper, and the keyboard
// "edit mode" in common/CASExampleEditor, so this file can stay focused on the
// BACnet logic.
// =============================================================================

#include "CASExampleHelper.h"
#include "CASExampleEditor.h"
#include "CASBACnetStackExampleConstants.h"
#include "CASBACnetStackDLL.h" // the CAS BACnet Stack C API (BACnetStack_*)

#include <stdio.h>
#include <string.h>

#if defined(_WIN32)
#include <windows.h> // Sleep()
#else
#include <unistd.h>  // usleep()
#endif

using namespace CASBACnetStackExampleConstants;

// -----------------------------------------------------------------------------
// 1. Example + device configuration
// -----------------------------------------------------------------------------
static const char* APP_NAME = "BACnet B-SS (Smart Sensor) Example - C++";
static const char* APP_VERSION = "1.0.1";

// The device instance. BACnet requires this to be configurable, so it defaults
// to 389001 and can be overridden on the command line with --deviceID.
static uint32_t g_deviceInstance = 389001;

// Your BACnet Vendor Identifier. 389 = Chipkin Automation Systems; change this
// to YOUR company's vendor ID before shipping a product. Vendor IDs are assigned
// by ASHRAE - request one (free) at https://bacnet.org/assigned-vendor-ids/.
// Update VENDOR_NAME below to match.
static const uint32_t VENDOR_IDENTIFIER = 389;
static const char* DEVICE_NAME = "Rainbow";
static const char* DEVICE_DESCRIPTION =
    "Chipkin CAS BACnet Stack example - B-SS (Smart Sensor) profile. "
    "Demonstrates DS-RP-B: ReadProperty plus Who-Is/I-Am with read-only sensor objects.";

// Device identity strings (read by clients, and used to populate I-Am).
static const char* VENDOR_NAME = "Chipkin Automation Systems";
static const char* MODEL_NAME = "CAS BACnet Stack Example - B-SS";
static const char* FIRMWARE_REVISION = "1.0.0";
static const char* APPLICATION_SOFTWARE_VERSION = "1.0.0";

// The sensor objects (all instance 1) and their colour names.
static const uint32_t ANALOG_INPUT_INSTANCE = 1;       // "Bronze"
static const uint32_t BINARY_INPUT_INSTANCE = 1;       // "Emerald"
static const uint32_t MULTI_STATE_INPUT_INSTANCE = 1;  // "Hot Pink"
static const uint32_t MULTI_STATE_INPUT_NUMBER_OF_STATES = 3;

// The Network Port object - every BACnet device must have one. It represents
// the BACnet/IP port this device communicates on.
static const uint32_t NETWORK_PORT_INSTANCE = 1;       // "Vermilion"
static const uint32_t MAX_APDU_LENGTH = 1476;          // BACnet/IP APDU length

// BACnet/IP addressing the Network Port reports. The IP address and subnet mask
// are filled in at start-up from the host's primary interface; the gateway is
// left unset (0.0.0.0) for this example. The stack also uses IP_Address +
// BACnet_IP_UDP_Port to build the port's MAC_Address automatically.
static uint8_t g_ipAddress[4] = { 0, 0, 0, 0 };
static uint8_t g_ipSubnetMask[4] = { 0, 0, 0, 0 };
static uint8_t g_ipDefaultGateway[4] = { 0, 0, 0, 0 };
static uint16_t g_bacnetIpUdpPort = 47808;

// Analog Input 1's live present value (degrees Celsius). Starts at 21.5 and is
// changed from the keyboard in "edit mode" (handled by common/CASExampleEditor).
// A real sensor would update this from hardware instead.
static float g_analogInput1Value = 21.5f;

// Binary Input 1's live present value (0 = inactive, 1 = active). Also editable
// from the keyboard. A real device would set this from a contact / relay input.
static uint32_t g_binaryInput1Value = 1;       // active

// Multi-State Input 1's live present value (a state, 1..3). Also editable from
// the keyboard. A real device would map this to a discrete sensor state.
static uint32_t g_multiStateInput1Value = 1;   // state 1

// -----------------------------------------------------------------------------
// 2. Property "get" callbacks
//
// The stack calls these when a client reads a property. For each data type the
// stack uses a separate callback. We return true (and fill *value) when we
// recognise the (object, property) pair, and false otherwise so the stack
// answers with the proper BACnet error.
// -----------------------------------------------------------------------------

// REAL (floating point) callback.
//   PROPERTY_IDENTIFIER_PRESENT_VALUE (85): an object's current value. For an
//   Analog Input it is the live sensor reading (here, degrees Celsius).
bool GetPropertyReal(const uint32_t deviceInstance, const uint16_t objectType,
                     const uint32_t objectInstance, const uint32_t propertyIdentifier,
                     float* value, const bool useArrayIndex,
                     const uint32_t propertyArrayIndex) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    if (deviceInstance == g_deviceInstance &&
        objectType == OBJECT_TYPE_ANALOG_INPUT &&
        objectInstance == ANALOG_INPUT_INSTANCE &&
        propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
        // ON REAL HARDWARE: return the live sensor reading here. Read it from a
        // cached variable that your hardware updates (as g_analogInput1Value is),
        // NOT directly from a slow/blocking device (I2C, SPI, ADC conversion):
        // this callback runs on the BACnetStack_Tick() thread, so blocking it
        // delays all BACnet processing. Sample the sensor on a timer/another
        // thread and just hand back the latest value from here.
        *value = g_analogInput1Value;
        return true;
    }
    return false;
}

// ENUMERATED callback - serves properties whose value is one of a fixed set of
// named codes. This example answers four of them; each is described at its case.
bool GetPropertyEnumerated(const uint32_t deviceInstance, const uint16_t objectType,
                           const uint32_t objectInstance, const uint32_t propertyIdentifier,
                           uint32_t* value, const bool useArrayIndex,
                           const uint32_t propertyArrayIndex) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    if (objectType == OBJECT_TYPE_BINARY_INPUT &&
        objectInstance == BINARY_INPUT_INSTANCE) {
        // PROPERTY_IDENTIFIER_PRESENT_VALUE (85): a Binary Input's state,
        // 0 = inactive, 1 = active.
        if (propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
            *value = g_binaryInput1Value; // live value (edit mode toggles it)
            return true;
        }
        // PROPERTY_IDENTIFIER_POLARITY (84): whether the physical signal is read
        // as-is (NORMAL) or inverted (REVERSE). A required Binary Input property.
        if (propertyIdentifier == PROPERTY_IDENTIFIER_POLARITY) {
            *value = POLARITY_NORMAL;
            return true;
        }
    }
    // PROPERTY_IDENTIFIER_UNITS (117): the engineering units of an Analog object's
    // Present_Value (here, degrees Celsius).
    if (objectType == OBJECT_TYPE_ANALOG_INPUT &&
        objectInstance == ANALOG_INPUT_INSTANCE &&
        propertyIdentifier == PROPERTY_IDENTIFIER_UNITS) {
        *value = ENGINEERING_UNITS_DEGREES_CELSIUS;
        return true;
    }
    // PROPERTY_IDENTIFIER_BACNET_IP_MODE (408): a BACnet/IP Network Port's role -
    // NORMAL (an ordinary BACnet/IP node), FOREIGN (a Foreign Device that
    // registers with a BBMD), or BBMD. This device is an ordinary node.
    if (objectType == OBJECT_TYPE_NETWORK_PORT &&
        objectInstance == NETWORK_PORT_INSTANCE &&
        propertyIdentifier == PROPERTY_IDENTIFIER_BACNET_IP_MODE) {
        *value = BACNET_IP_MODE_NORMAL;
        return true;
    }
    return false;
}

// UNSIGNED INTEGER callback - serves unsigned-integer properties: the Multi-State
// Input's state, the Device's Vendor_Identifier, and several Network Port numbers.
// Each property identifier is described at its case below.
bool GetPropertyUnsignedInteger(const uint32_t deviceInstance, const uint16_t objectType,
                                const uint32_t objectInstance, const uint32_t propertyIdentifier,
                                uint32_t* value, const bool useArrayIndex,
                                const uint32_t propertyArrayIndex) {
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    if (objectType == OBJECT_TYPE_MULTI_STATE_INPUT &&
        objectInstance == MULTI_STATE_INPUT_INSTANCE) {
        // PROPERTY_IDENTIFIER_PRESENT_VALUE (85): a Multi-State object's current
        // state, an integer in 1..Number_Of_States.
        if (propertyIdentifier == PROPERTY_IDENTIFIER_PRESENT_VALUE) {
            *value = g_multiStateInput1Value; // live value (edit mode steps it)
            return true;
        }
        // PROPERTY_IDENTIFIER_NUMBER_OF_STATES (74): how many states the object
        // has; Present_Value is valid as 1..this. A required property.
        if (propertyIdentifier == PROPERTY_IDENTIFIER_NUMBER_OF_STATES) {
            *value = MULTI_STATE_INPUT_NUMBER_OF_STATES;
            return true;
        }
        // PROPERTY_IDENTIFIER_STATE_TEXT (110): an array of human-readable labels,
        // one per state. The stack asks for the array LENGTH here (array index 0)
        // before reading each element via GetPropertyCharString.
        if (propertyIdentifier == PROPERTY_IDENTIFIER_STATE_TEXT &&
            useArrayIndex && propertyArrayIndex == 0) {
            *value = MULTI_STATE_INPUT_NUMBER_OF_STATES;
            return true;
        }
    }
    // PROPERTY_IDENTIFIER_VENDOR_IDENTIFIER (120): the manufacturer's
    // ASHRAE-assigned vendor ID (389 = Chipkin). The stack also uses it in I-Am.
    if (objectType == OBJECT_TYPE_DEVICE && objectInstance == g_deviceInstance &&
        propertyIdentifier == PROPERTY_IDENTIFIER_VENDOR_IDENTIFIER) {
        *value = VENDOR_IDENTIFIER;
        return true;
    }
    if (objectType == OBJECT_TYPE_NETWORK_PORT && objectInstance == NETWORK_PORT_INSTANCE) {
        // PROPERTY_IDENTIFIER_APDU_LENGTH (399): the largest APDU (bytes) the port
        // accepts - 1476 for BACnet/IP.
        if (propertyIdentifier == PROPERTY_IDENTIFIER_APDU_LENGTH) {
            *value = MAX_APDU_LENGTH;
            return true;
        }
        // PROPERTY_IDENTIFIER_REFERENCE_PORT (483): the port this one layers on;
        // "none" for the lowest (physical) layer, as here.
        if (propertyIdentifier == PROPERTY_IDENTIFIER_REFERENCE_PORT) {
            *value = NETWORK_PORT_REFERENCE_PORT_NONE;
            return true;
        }
        // PROPERTY_IDENTIFIER_BACNET_IP_UDP_PORT (412): the UDP port the device
        // listens on for BACnet/IP (default 47808 / 0xBAC0).
        if (propertyIdentifier == PROPERTY_IDENTIFIER_BACNET_IP_UDP_PORT) {
            *value = g_bacnetIpUdpPort;
            return true;
        }
    }
    return false;
}

// BOOLEAN callback.
//   PROPERTY_IDENTIFIER_OUT_OF_SERVICE (81): when true, the object is decoupled
//   from the physical world (its Present_Value can be written for testing). This
//   read-only sensor is never out of service, so it always returns false. It is a
//   required property of every input object and of the Network Port.
bool GetPropertyBool(const uint32_t deviceInstance, const uint16_t objectType,
                     const uint32_t objectInstance, const uint32_t propertyIdentifier,
                     bool* value, const bool useArrayIndex,
                     const uint32_t propertyArrayIndex) {
    (void)objectInstance;
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    if (deviceInstance != g_deviceInstance) {
        return false;
    }
    if (propertyIdentifier == PROPERTY_IDENTIFIER_OUT_OF_SERVICE &&
        (objectType == OBJECT_TYPE_ANALOG_INPUT ||
         objectType == OBJECT_TYPE_BINARY_INPUT ||
         objectType == OBJECT_TYPE_MULTI_STATE_INPUT ||
         objectType == OBJECT_TYPE_NETWORK_PORT)) {
        *value = false;
        return true;
    }
    return false;
}

// OCTET STRING - the Network Port's BACnet/IP addressing. The stack cannot know
// the host's IP, so the application must supply IP_Address and IP_Subnet_Mask
// (and IP_Default_Gateway). Each is four octets. The stack also reads IP_Address
// (with BACnet_IP_UDP_Port) to build the port's six-octet MAC_Address.
bool GetPropertyOctetString(const uint32_t deviceInstance, const uint16_t objectType,
                            const uint32_t objectInstance, const uint32_t propertyIdentifier,
                            uint8_t* value, uint32_t* valueElementCount,
                            const uint32_t maxElementCount, const bool useArrayIndex,
                            const uint32_t propertyArrayIndex) {
    (void)useArrayIndex;
    (void)propertyArrayIndex;
    if (deviceInstance != g_deviceInstance ||
        objectType != OBJECT_TYPE_NETWORK_PORT ||
        objectInstance != NETWORK_PORT_INSTANCE ||
        maxElementCount < 4) {
        return false;
    }
    // PROPERTY_IDENTIFIER_IP_ADDRESS (400) / IP_SUBNET_MASK (411) /
    // IP_DEFAULT_GATEWAY (401): the Network Port's IPv4 settings, each a 4-octet
    // string. The stack also builds the port's MAC_Address from IP_Address + the
    // BACnet_IP_UDP_Port.
    const uint8_t* source = NULL;
    switch (propertyIdentifier) {
        case PROPERTY_IDENTIFIER_IP_ADDRESS:         source = g_ipAddress; break;
        case PROPERTY_IDENTIFIER_IP_SUBNET_MASK:     source = g_ipSubnetMask; break;
        case PROPERTY_IDENTIFIER_IP_DEFAULT_GATEWAY: source = g_ipDefaultGateway; break;
        default: return false;
    }
    memcpy(value, source, 4);
    *valueElementCount = 4;
    return true;
}

// Small helper: copy a C string into the stack's character-string buffer and
// set the element count + encoding. Returns true (so callers can `return`).
static bool ReturnCharacterString(const char* text, char* value,
                                  uint32_t* valueElementCount,
                                  const uint32_t maxElementCount,
                                  uint8_t* encodingType) {
    uint32_t length = (uint32_t)strlen(text);
    if (length > maxElementCount) {
        length = maxElementCount;
    }
    memcpy(value, text, length);
    *valueElementCount = length;
    *encodingType = CHARACTER_STRING_ENCODING_UTF8;
    return true;
}

// CHARACTER STRING callback - serves text properties:
//   PROPERTY_IDENTIFIER_OBJECT_NAME (77): each object's name (the colour names).
//   PROPERTY_IDENTIFIER_STATE_TEXT (110): a Multi-State Input's per-state labels.
//   PROPERTY_IDENTIFIER_DESCRIPTION (28): the Device's free-text description.
//   PROPERTY_IDENTIFIER_VENDOR_NAME (121) / MODEL_NAME (70) / FIRMWARE_REVISION
//   (44) / APPLICATION_SOFTWARE_VERSION (12): Device identity strings, also
//   surfaced during Who-Is / I-Am discovery.
bool GetPropertyCharString(const uint32_t deviceInstance, const uint16_t objectType,
                           const uint32_t objectInstance, const uint32_t propertyIdentifier,
                           char* value, uint32_t* valueElementCount,
                           const uint32_t maxElementCount, uint8_t* encodingType,
                           const bool useArrayIndex, const uint32_t propertyArrayIndex) {
    if (deviceInstance != g_deviceInstance) {
        return false;
    }

    // State_Text (optional) - one label per state of the Multi-State Input. It is
    // a BACnet array, so the stack asks for one element at a time by index
    // (1..Number_Of_States). Present_Value 1 -> "On", 2 -> "Off", 3 -> "Auto".
    if (objectType == OBJECT_TYPE_MULTI_STATE_INPUT &&
        objectInstance == MULTI_STATE_INPUT_INSTANCE &&
        propertyIdentifier == PROPERTY_IDENTIFIER_STATE_TEXT && useArrayIndex) {
        static const char* const stateText[] = { "On", "Off", "Auto" };
        if (propertyArrayIndex >= 1 && propertyArrayIndex <= MULTI_STATE_INPUT_NUMBER_OF_STATES) {
            return ReturnCharacterString(stateText[propertyArrayIndex - 1], value,
                                         valueElementCount, maxElementCount, encodingType);
        }
        return false;
    }

    // Object_Name - the colour name for each object.
    if (propertyIdentifier == PROPERTY_IDENTIFIER_OBJECT_NAME) {
        if (objectType == OBJECT_TYPE_DEVICE && objectInstance == g_deviceInstance) {
            return ReturnCharacterString(DEVICE_NAME, value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_ANALOG_INPUT && objectInstance == ANALOG_INPUT_INSTANCE) {
            return ReturnCharacterString("Bronze", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_BINARY_INPUT && objectInstance == BINARY_INPUT_INSTANCE) {
            return ReturnCharacterString("Emerald", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_MULTI_STATE_INPUT && objectInstance == MULTI_STATE_INPUT_INSTANCE) {
            return ReturnCharacterString("Hot Pink", value, valueElementCount, maxElementCount, encodingType);
        }
        if (objectType == OBJECT_TYPE_NETWORK_PORT && objectInstance == NETWORK_PORT_INSTANCE) {
            return ReturnCharacterString("Vermilion", value, valueElementCount, maxElementCount, encodingType);
        }
    }

    // The remaining strings are all on the Device object - its identity, read
    // by clients and used to populate the device's I-Am / object list.
    if (objectType == OBJECT_TYPE_DEVICE && objectInstance == g_deviceInstance) {
        switch (propertyIdentifier) {
            case PROPERTY_IDENTIFIER_DESCRIPTION:
                return ReturnCharacterString(DEVICE_DESCRIPTION, value, valueElementCount, maxElementCount, encodingType);
            case PROPERTY_IDENTIFIER_VENDOR_NAME:
                return ReturnCharacterString(VENDOR_NAME, value, valueElementCount, maxElementCount, encodingType);
            case PROPERTY_IDENTIFIER_MODEL_NAME:
                return ReturnCharacterString(MODEL_NAME, value, valueElementCount, maxElementCount, encodingType);
            case PROPERTY_IDENTIFIER_FIRMWARE_REVISION:
                return ReturnCharacterString(FIRMWARE_REVISION, value, valueElementCount, maxElementCount, encodingType);
            case PROPERTY_IDENTIFIER_APPLICATION_SOFTWARE_VERSION:
                return ReturnCharacterString(APPLICATION_SOFTWARE_VERSION, value, valueElementCount, maxElementCount, encodingType);
            default:
                break;
        }
    }

    return false;
}

// -----------------------------------------------------------------------------
// 3. main()
// -----------------------------------------------------------------------------
int main(int argc, char** argv) {
    // Show printf output immediately, even when stdout is piped to a file.
    setvbuf(stdout, NULL, _IONBF, 0);

    // --- Command line + version --------------------------------------------
    const uint16_t port = CASExampleHelper::ParsePortArg(argc, argv, 47808);
    g_deviceInstance = CASExampleHelper::ParseDeviceIdArg(argc, argv, g_deviceInstance);
    CASExampleHelper::PrintVersion(APP_NAME, APP_VERSION);

    // --- Bind the BACnet/IP socket -----------------------------------------
    if (!CASExampleHelper::SetupUDP(port)) {
        return 1;
    }

    // Capture the BACnet/IP addressing the Network Port object will report.
    g_bacnetIpUdpPort = port;
    if (!CASExampleHelper::GetLocalIPv4(g_ipAddress, g_ipSubnetMask)) {
        printf("FYI: could not read a local IPv4 address; Network Port IP_Address "
               "will report 0.0.0.0.\n");
    }

    // --- Register callbacks -------------------------------------------------
    // The transport + time callbacks are shared boilerplate.
    CASExampleHelper::RegisterCommonCallbacks();
    // The property callbacks are specific to this example.
    BACnetStack_RegisterCallbackGetPropertyReal(GetPropertyReal);
    BACnetStack_RegisterCallbackGetPropertyEnumerated(GetPropertyEnumerated);
    BACnetStack_RegisterCallbackGetPropertyUnsignedInteger(GetPropertyUnsignedInteger);
    BACnetStack_RegisterCallbackGetPropertyCharacterString(GetPropertyCharString);
    BACnetStack_RegisterCallbackGetPropertyBool(GetPropertyBool);
    BACnetStack_RegisterCallbackGetPropertyOctetString(GetPropertyOctetString);

    // --- Create the device --------------------------------------------------
    if (!BACnetStack_AddDevice(g_deviceInstance)) {
        printf("Error: Failed to add the Device %u.\n", g_deviceInstance);
        return 1;
    }

    // Enable ReadProperty (DS-RP-B) - the one mandatory service for B-SS.
    // We set it explicitly to make the profile requirement obvious.
    //
    // We deliberately do NOT enable WriteProperty, ReadPropertyMultiple,
    // SubscribeCOV, or any alarm/event service: a Smart Sensor does not require
    // them, so a faithful B-SS example leaves them off.
    if (!BACnetStack_SetServiceEnabled(g_deviceInstance, SERVICE_READ_PROPERTY, true)) {
        printf("Error: Failed to enable the ReadProperty service.\n");
        return 1;
    }

    // --- Add the read-only sensor objects -----------------------------------
    // Every stack setup call returns a bool; a real device should always check
    // it, so this example does too.
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_ANALOG_INPUT, ANALOG_INPUT_INSTANCE)) {
        printf("Error: Failed to add Analog Input 1 (Bronze).\n");
        return 1;
    }
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_BINARY_INPUT, BINARY_INPUT_INSTANCE)) {
        printf("Error: Failed to add Binary Input 1 (Emerald).\n");
        return 1;
    }
    if (!BACnetStack_AddObject(g_deviceInstance, OBJECT_TYPE_MULTI_STATE_INPUT, MULTI_STATE_INPUT_INSTANCE)) {
        printf("Error: Failed to add Multi-State Input 1 (Hot Pink).\n");
        return 1;
    }

    // --- Add the Network Port object ----------------------------------------
    // Every BACnet device (Protocol_Revision 17+) must have at least one Network
    // Port object describing the port it talks on. This one is the BACnet/IP
    // application port; it is the lowest layer, so its reference port is "none".
    if (!BACnetStack_AddNetworkPortObject(
            g_deviceInstance, NETWORK_PORT_INSTANCE,
            NETWORK_PORT_NETWORK_TYPE_IPV4,
            NETWORK_PORT_PROTOCOL_LEVEL_BACNET_APPLICATION,
            NETWORK_PORT_REFERENCE_PORT_NONE)) {
        printf("Error: Failed to add Network Port 1 (Vermilion).\n");
        return 1;
    }

    // --- Enable the OPTIONAL properties we choose to expose ------------------
    // The stack automatically enables an object's REQUIRED properties when the
    // object is added (AddObject / AddNetworkPortObject) - so Units, Polarity,
    // Number_Of_States, Out_Of_Service, and the Network Port's BACnet/IP
    // addressing (IP_Address, IP_Subnet_Mask, BACnet_IP_UDP_Port, ...) are
    // already enabled; our Get* callbacks just supply their values. Only
    // OPTIONAL properties need SetPropertyEnabled. State_Text is optional on a
    // Multi-State Input, so we enable it here (and serve it in GetPropertyCharString).
    BACnetStack_SetPropertyEnabled(g_deviceInstance, OBJECT_TYPE_MULTI_STATE_INPUT,
                                   MULTI_STATE_INPUT_INSTANCE, PROPERTY_IDENTIFIER_STATE_TEXT, true);

    // Who-Is is answered automatically. The spec also requires a device to
    // announce itself on start-up, so broadcast an unsolicited I-Am now (to the
    // local subnet broadcast - the Network Port's own network).
    CASExampleHelper::SendIAm(g_deviceInstance);

    printf("FYI: Device %u (\"%s\") ready. Vendor ID %u. Press 'e' to edit values, 'h' for help.\n",
           g_deviceInstance, DEVICE_NAME, VENDOR_IDENTIFIER);

    // --- Register the objects the user can change from the keyboard ---------
    // The shared helper owns the whole "edit mode" UI (press 'e', pick an object,
    // change it with up/down). We just point it at the live value variables our
    // Get callbacks already return; after each change the helper calls
    // BACnetStack_UpdateValue so the stack re-evaluates COV / alarms. Keeping all
    // of that in common/ is what lets this main.cpp stay short.
    CASExampleEditor::SetAppInfo(APP_NAME, APP_VERSION);
    CASExampleEditor::RegisterEditableReal(
        g_deviceInstance, OBJECT_TYPE_ANALOG_INPUT, ANALOG_INPUT_INSTANCE,
        "Analog Input 1 (Bronze)", &g_analogInput1Value,
        1.1f /*step*/, -50.0f /*min C*/, 150.0f /*max C*/);
    CASExampleEditor::RegisterEditableBinary(
        g_deviceInstance, OBJECT_TYPE_BINARY_INPUT, BINARY_INPUT_INSTANCE,
        "Binary Input 1 (Emerald)", &g_binaryInput1Value);
    CASExampleEditor::RegisterEditableMultiState(
        g_deviceInstance, OBJECT_TYPE_MULTI_STATE_INPUT, MULTI_STATE_INPUT_INSTANCE,
        "Multi-State Input 1 (Hot Pink)", &g_multiStateInput1Value,
        MULTI_STATE_INPUT_NUMBER_OF_STATES);

    // --- Run the stack ------------------------------------------------------
    // BACnetStack_Tick() processes incoming messages and timers. Call it
    // continuously; ProcessConsoleInput() handles all keyboard interaction
    // (h help, q quit, e edit object values) and returns false on quit.
    bool running = true;
    while (running) {
        BACnetStack_Tick();

        if (!CASExampleEditor::ProcessConsoleInput()) {
            running = false;
        }

#if defined(_WIN32)
        Sleep(1); // 1 ms - be a good citizen, don't spin the CPU
#else
        usleep(1000);
#endif
    }

    CASExampleEditor::RestoreInput();
    CASExampleHelper::ShutdownUDP();
    return 0;
}
